name: "Post Pre-Release"

on:
  push:
    tags:
       - "pack-version-update"

jobs:
  pre-release:
    name: "Create Pre-Release"
    runs-on: "ubuntu-latest"

    steps:
    - name: "Create Release"
      run: |
         git push --delete origin pack-version-update
         rm -r increasePackVersion.php
         rm -r .github/
         rm -r .gitignore
         rm -r README.md
         echo "done!"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest" #${{ github.ref }}
          prerelease: true
          title: "Development Release"
