name: "Post Pre-Release"

on:
  push:
    tags:
      - "pack-version-change"
    #branches:
    #  - "main"

jobs:
  pre-release:
    name: "Create Pre-Release"
    runs-on: "ubuntu-latest"

    steps:
    - name: "Create Release"
      run: |
         rm -r increasePackVersion.php
         rm -r .github/
         rm -r .gitignore
         rm -r README.md
#         git push --delete origin pack-version-change
         echo "done!"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest" #${{ github.ref }}
          prerelease: true
          title: "Development Release"
